project:
  type: website

website:
  title: "R + databases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



