project:
  type: website
  output-dir: docs

website:
  title: "R-DBI"
  description: "R + databases"
  site-url: https://r-dbi.org/
  page-footer:
    left:
      - text: "© Licence MIT."
    right:
      - text: "Sponsored by the R Consortium."
        href: https://www.r-consortium.org/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: backends/index.qmd
        text: Backends

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

comments:
  giscus:
    repo: r-dbi/r-dbi.org

